[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi#feature/proton-picosdk-support
board = proton
framework = picosdk
build_src_flags = -O0 -DPICO_RP2350B=1 -Wl,"$PROJECT_SRC_DIR/autotest.o" -Wl,"$PROJECT_SRC_DIR/drum_machine.o"
debug_tool = picoprobe
upload_protocol = picoprobe
monitor_speed = 115200
build_flags = -DPICO_DEFAULT_UART=0 -DPICO_DEFAULT_UART_TX_PIN=0 -DPICO_DEFAULT_UART_RX_PIN=1